title: VIGIL Risk Intelligence
description: Enterprise Risk Intelligence with Three Schema Strategies (Structured/Semi-Structured/Unstructured) and Dual-Source Analysis (Claude AI + Grok Intelligence)
sdk: docker
pinned: false
tags:
  - risk-management
  - enterprise
  - ai
  - transformers
  - supabase
  - structured-data
  - semi-structured-data
  - unstructured-data
  - schema-on-write
  - schema-on-read
  - hybrid-schema
  - vigil-summary
  - alerts
  - dual-path-analysis
  - claude-ai
  - grok-intelligence
  - distilbert
  - pgvector
  - semantic-search

# Environment variables
env:
  - name: XAI_API_KEY
    description: X.AI API key for Grok integration
  - name: SUPABASE_URL
    description: Supabase project URL
  - name: SUPABASE_KEY
    description: Supabase anon key
  - name: ANTHROPIC_API_KEY
    description: Anthropic API key for Claude AI integration
  - name: FLASK_ENV
    default: production

# Space configuration
persistent_storage:
  - path: /app/data
    size: 10

# Hardware requirements
hardware:
  - cpu-basic
  - cpu-upgrade
  - t4
  - a10g

# Health check
healthcheck:
  enabled: true
  endpoint: /api/health